default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  pool: 5

development:
  <<: *default
  database: crypto_trading_game_development

test:
  <<: *default
  database: crypto_trading_game_test

production:
  <<: *default
  database: crypto_trading_game_production
